@startuml ExportData
|Администратор|
start
split
  :Экспортировать информацию
  о мероприятии, секциях,
  список участников по секциям
  (программа);
split again
  :Экспортировать данные об участниках;
split again
  :Экспортировать тексты докладов;
end split
stop
@enduml
