@startuml CheckCertificate
|Пользователь|
start
split
  :Открыть сайт;
  :Ввести номер сертификата участника;
split again
  :Открыть уникальную ссылку;
end split
:Просмотреть информацию о сертификате;
stop
@enduml
