@startuml SubscribeToEvent
|Пользователь|
start
if (Пользователь зарегистрирован?) then (да)
else (нет)
  #Plum:Регистрация в системе|
  detach
endif
if (Пользователь знает логин/пароль?) then (да)
  :Ввести данные, выполнить вход;
else (нет)
  #Plum:Восстановление пароля|
  detach
endif
:Выбрать мероприятие;
:Подписаться на обновления новостей, информационные письма и программу;
stop
@enduml
