@startuml Participate
|Пользователь|
start
if (Пользователь зарегистрирован?) then (да)
else (нет)
  #Plum:Регистрация в системе|
  detach
endif
if (Пользователь знает логин/пароль?) then (да)
  :Ввести данные, выполнить вход;
else (нет)
  #Plum:Восстановление пароля|
  detach
endif
:Выбрать мероприятие;
:Заполнить форму заявки;
|#AntiqueWhite|Администратор|
:Подтвердить заявку;
|Пользователь|
:Получить подтверждение заявки;
stop
@enduml
