@startuml RestorePassword
|Пользователь|
start
:Выбрать опцию "восстановление пароля";
:Ввести email;
:Получить на email ссылку для сброса пароля;
:Открыть ссылку для сброса пароля;
:Установить новый пароль;
stop
@enduml
