@startuml SubscribeToPresentation
|Пользователь|
start
if (Пользователь зарегистрирован?) then (да)
else (нет)
  #Plum:Регистрация в системе|
  detach
endif
if (Пользователь знает логин/пароль?) then (да)
  :Ввести данные, выполнить вход;
else (нет)
  #Plum:Восстановление пароля|
  detach
endif
:Выбрать мероприятие;
:Просмотреть список заявок;
:Подписаться на конкретные заявки;
|#AntiqueWhite|Система|
:Сформировать список в формате
"название; секция; ~время"
по выбранным заявкам;
|Пользователь|
:Получить на email список выбранных заявок;
stop
@enduml
